workflows:
  ios-release:
    name: Budget Tracker iOS
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic-ios-release-v2

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ctre2.budgettracker

    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Install dependencies
        script: |
          flutter pub get
          find . -name "Podfile" -execdir pod install \;
      - name: Build iOS IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=$HOME/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - direction@novasoft.solutions
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
